# secrets.toml content

# Your Gemini API Key from Google AI Studio
GEMINI_API_KEY = "dummy"

# Your Yelp API Key (The one currently hardcoded in your Python script)
# It's much safer to store this here too!
YELP_API_KEY = "dummy"